export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Toaster } from "@/components/ui/toaster"

import "./globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className="bg-emerald-300/10" >
        {children}
        <Toaster />
      </body>
    </html>
  )
}
